name: graphigl-CI

on:
  push:
    # Run on all branches
    branches:
      - '*'
  #   # Run only if files modified are not docs
    paths-ignore:
      - '*.md'
  pull_request:
    # Run on all branches
    branches:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.DEPLOY_SECRET }}

jobs:
  buildAndTest:
    continue-on-error: true
    name: Build & Test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Use cashe
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      # Install
      - name: INSTALL
        run: npm ci

      # Lint
      - name: LINT
        run: npm run lint

      # Build
      - name: BUILD
        run: npm run build

      # Test
      - name: TEST VITEST
        run: npm run test
