name: graphigl-CI

on:
  - push
  - pull_request

env:
  CI: true

jobs:
  test:
    rush-on: ubuntu-latest
    steps:
      name: get repository code
      uses: actions/checkout@v3
      name: install dependies
      run: npm ci
      name: test
      run: npm run test
